# Generated by Django 5.1.3 on 2024-12-16 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='save_signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(blank=True, max_length=100, null=True)),
                ('s_email', models.CharField(blank=True, max_length=100, null=True)),
                ('s_pass', models.CharField(blank=True, max_length=100, null=True)),
                ('s_repass', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
