# Generated by Django 5.1.3 on 2024-12-16 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='save_signup',
            old_name='s_email',
            new_name='t_email',
        ),
        migrations.RenameField(
            model_name='save_signup',
            old_name='s_name',
            new_name='t_name',
        ),
        migrations.RenameField(
            model_name='save_signup',
            old_name='s_pass',
            new_name='t_pass',
        ),
        migrations.RenameField(
            model_name='save_signup',
            old_name='s_repass',
            new_name='t_repass',
        ),
    ]
