# Generated by Django 5.1.3 on 2024-12-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_rename_s_email_save_signup_t_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=100)),
                ('batch_name', models.CharField(max_length=100)),
                ('faculty_name', models.CharField(max_length=100)),
                ('parent_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
