# Generated by Django 5.1.3 on 2024-12-18 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='attendence',
        ),
    ]
