# Generated by Django 5.1.3 on 2024-12-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_delete_attendence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='batch_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='course_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='faculty_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
