# Generated by Django 5.1.3 on 2024-12-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_remove_attendance_date_attendance_attendance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='student_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
