# Generated by Django 5.1.3 on 2024-12-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_attendance_student_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='studnt_signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studnt_name', models.CharField(blank=True, max_length=100, null=True)),
                ('studnt_email', models.CharField(blank=True, max_length=100, null=True)),
                ('studnt_pass', models.CharField(blank=True, max_length=100, null=True)),
                ('studnt_repass', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
