# Generated by Django 5.1.3 on 2025-01-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_studnt_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_sname', models.CharField(blank=True, max_length=100, null=True)),
                ('l_cname', models.CharField(blank=True, max_length=100, null=True)),
                ('l_fname', models.CharField(blank=True, max_length=100, null=True)),
                ('l_ndate', models.CharField(blank=True, max_length=100, null=True)),
                ('l_reason', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
