# Generated by Django 5.1.3 on 2025-01-04 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_student_leave'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student_leave',
            new_name='student_leavedb',
        ),
    ]
