# Generated by Django 5.1.3 on 2025-01-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_rename_student_leave_student_leavedb'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_leavedb',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
