# Generated by Django 5.1.3 on 2025-01-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_student_leavedb_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_leavedb',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('denied', 'Denied'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
