# Generated by Django 5.1.3 on 2025-01-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_leavedb',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Denied', 'Denied'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
