# Generated by Django 5.1.3 on 2024-11-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(blank=True, max_length=100, null=True)),
                ('hod', models.CharField(blank=True, max_length=100, null=True)),
                ('desc', models.TextField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
