# Generated by Django 5.1.3 on 2024-11-22 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amsapp', '0002_departmental'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departmental',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='status',
            new_name='code',
        ),
    ]
