# Generated by Django 5.1.3 on 2024-11-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsapp', '0004_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='coursedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(blank=True, max_length=100, null=True)),
                ('c_name', models.CharField(blank=True, max_length=100, null=True)),
                ('c_desc', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='course',
        ),
    ]
