# Generated by Django 5.1.3 on 2024-11-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsapp', '0006_remove_department_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='facultydb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(blank=True, max_length=100, null=True)),
                ('d_name', models.CharField(blank=True, max_length=100, null=True)),
                ('f_gender', models.CharField(blank=True, max_length=100, null=True)),
                ('f_dob', models.CharField(blank=True, max_length=100, null=True)),
                ('f_phn', models.CharField(blank=True, max_length=100, null=True)),
                ('f_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('f_add', models.TextField(blank=True, max_length=100, null=True)),
                ('f_pic', models.ImageField(blank=True, null=True, upload_to='Faculty_Images')),
            ],
        ),
    ]
