# Generated by Django 5.1.3 on 2024-11-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsapp', '0007_facultydb'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ds_name', models.CharField(blank=True, max_length=100, null=True)),
                ('s_gender', models.CharField(blank=True, max_length=100, null=True)),
                ('s_dob', models.CharField(blank=True, max_length=100, null=True)),
                ('s_phn', models.CharField(blank=True, max_length=100, null=True)),
                ('s_add', models.TextField(blank=True, max_length=100, null=True)),
                ('s_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('s_pic', models.ImageField(blank=True, null=True, upload_to='Student_Images')),
            ],
        ),
    ]
