# Generated by Django 5.1.3 on 2024-11-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsapp', '0008_studentdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdb',
            name='sp_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
