# Generated by Django 5.1.3 on 2024-11-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsapp', '0009_studentdb_sp_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedb',
            name='fa_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
