# Generated by Django 5.1.3 on 2024-12-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsapp', '0010_coursedb_fa_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedb',
            name='c_desc',
        ),
        migrations.RemoveField(
            model_name='coursedb',
            name='department_name',
        ),
        migrations.RemoveField(
            model_name='coursedb',
            name='fa_name',
        ),
        migrations.AddField(
            model_name='coursedb',
            name='c_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursedb',
            name='c_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
