# Generated by Django 5.1.3 on 2024-12-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsapp', '0011_remove_coursedb_c_desc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursedb',
            old_name='c_end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='coursedb',
            old_name='c_start',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='coursedb',
            name='c_name',
        ),
        migrations.AddField(
            model_name='coursedb',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
