# Generated by Django 5.1.3 on 2024-12-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsapp', '0012_rename_c_end_coursedb_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedb',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='coursedb',
            name='start_date',
        ),
        migrations.AddField(
            model_name='coursedb',
            name='bname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
