# Generated by Django 5.1.3 on 2024-12-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsapp', '0013_remove_coursedb_end_date_remove_coursedb_start_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='department',
        ),
        migrations.RenameField(
            model_name='facultydb',
            old_name='d_name',
            new_name='batch_name',
        ),
        migrations.AddField(
            model_name='facultydb',
            name='course_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facultydb',
            name='f_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
