# Generated by Django 5.1.3 on 2024-12-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsapp', '0014_delete_department_rename_d_name_facultydb_batch_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdb',
            old_name='ds_name',
            new_name='b_name',
        ),
        migrations.AddField(
            model_name='studentdb',
            name='c_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentdb',
            name='s_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
