# Generated by Django 5.1.3 on 2024-12-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsapp', '0015_rename_ds_name_studentdb_b_name_studentdb_c_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdb',
            name='s_fac',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
