# Generated by Django 5.1.3 on 2024-12-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsapp', '0016_studentdb_s_fac'),
    ]

    operations = [
        migrations.CreateModel(
            name='notific',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificat', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
