# Generated by Django 5.1.3 on 2024-12-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsapp', '0017_notific'),
    ]

    operations = [
        migrations.AddField(
            model_name='notific',
            name='facult_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
