from django.urls import path
from amsapp import views
urlpatterns=[
    path('adminpage/',views.adminpage,name="adminpage"),

    path('add_course/',views.add_course,name="add_course"),
    path('save_course/',views.save_course,name="save_course"),
    path('view_course/',views.view_course,name="view_course"),
    path('add_faculty/',views.add_faculty,name="add_faculty"),
    path('add_student/',views.add_student,name="add_student"),
    path('save_faculty/',views.save_faculty,name="save_faculty"),
    path('save_student/',views.save_student,name="save_student"),
    path('view_faculty/', views.view_faculty, name="view_faculty"),
    path('view_student/', views.view_student, name="view_student"),
    path('add_announcements/', views.add_announcements, name="add_announcements"),
    path('View_Announcments/', views.View_Announcments, name="View_Announcments"),
    path('Save_Announcements/', views.Save_Announcements, name="Save_Announcements"),
    path('save_student_leave/', views.save_student_leave, name="save_student_leave"),
    path('save_studattendance/', views.save_studattendance, name="save_studattendance"),

    path('edit_course/<int:pk>/', views.edit_course, name="edit_course"),
    path('edit_faculty/<int:f_id>/', views.edit_faculty, name="edit_faculty"),
    path('edit_student/<int:s_id>/', views.edit_student, name="edit_student"),
    path('edit_announcements/<int:a_id>/', views.edit_announcements, name="edit_announcements"),
    path('edit_teacher_signup/<int:ts_id>/', views.edit_teacher_signup, name="edit_teacher_signup"),
    path('edit_studentleave/<int:sl_id>/', views.edit_studentleave, name="edit_studentleave"),
    path('edit_studentattend/<int:sa_id>/', views.edit_studentattend, name="edit_studentattend"),

    path('update_course/<int:co_id>/', views.update_course, name="update_course"),
    path('update_faculty/<int:f_id>/', views.update_faculty, name="update_faculty"),
    path('update_student/<int:s_id>/', views.update_student, name="update_student"),
    path('update_announcements/<int:an_id>/', views.update_announcements, name="update_announcements"),
    path('update_student_signup/<int:ss_id>/', views.update_student_signup, name="update_student_signup"),
    path('update_teacher_signup/<int:ts_id>/', views.update_teacher_signup, name="update_teacher_signup"),
    path('update_studentleave/<int:sl_id>/', views.update_studentleave, name="update_studentleave"),

    path('delete_course/<int:c_id>/', views.delete_course, name="delete_course"),
    path('delete_faculty/<int:f_id>/', views.delete_faculty, name="delete_faculty"),
    path('delete_student/<int:s_id>/', views.delete_student, name="delete_student"),
    path('delete_announcements/<int:an_id>/', views.delete_announcements, name="delete_announcements"),
    path('delete_student_signup/<int:ss_id>/', views.delete_student_signup, name="delete_student_signup"),
    path('delete_teacher_signup/<int:ts_id>/', views.delete_teacher_signup, name="delete_teacher_signup"),
    path('delete_student_leave/<int:sl_id>/', views.delete_student_leave, name="delete_student_leave"),
    path('delete_studentattendance/<int:sa_id>/', views.delete_studentattendance, name="delete_studentattendance"),

    path('add_studentsignup/', views.add_studentsignup, name="add_studentsignup"),
    path('add_teacherignup/', views.add_teacherignup, name="add_teacherignup"),
    path('add_student_leave/', views.add_student_leave, name="add_student_leave"),
    path('add_studattendance/', views.add_studattendance, name="add_studattendance"),
    path('view_studentsignup/', views.view_studentsignup, name="view_studentsignup"),
    path('view_teachersignup/', views.view_teachersignup, name="view_teachersignup"),
    path('view_studentleave/', views.view_studentleave, name="view_studentleave"),
    path('view_studenattendence/', views.view_studenattendence, name="view_studenattendence"),
    path('save_student_signup/', views.save_student_signup, name="save_student_signup"),
    path('save_teacher_signup/', views.save_teacher_signup, name="save_teacher_signup"),

    path('edit_student_signup/<int:ss_id>/', views.edit_student_signup, name="edit_student_signup"),

    path('logins/', views.logins, name="logins"),
    path('admin_login/', views.admin_login, name="admin_login"),
    path('delete_logout/', views.delete_logout, name="delete_logout"),
    path("check_username/", views.check_username, name="check_username"),
    path("validate_login/", views.validate_login, name="validate_login"),
]